aws:
  region: us-east-1
  bedrock:
    model_id: anthropic.claude-3-sonnet-20240229-v1:0
    embedding_model_id: amazon.titan-embed-text-v1
  credentials:
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}

app:
  name: "ML Hybrid Theme Analysis"
  version: "1.0.0"
  debug: false
  host: "0.0.0.0"
  port: 8000

logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  file: "logs/app.log"
  rotation: "10 MB"
  retention: "30 days"

preprocessing:
  min_summary_length: 10
  max_summary_length: 2000
  supported_languages: ["en"]
  remove_html: true
  normalize_case: true
  remove_duplicates: true
  lemmatization: true
  remove_boilerplate: true

clustering:
  umap:
    n_neighbors: 15
    n_components: 2
    min_dist: 0.1
    metric: "cosine"
  hdbscan:
    min_cluster_size: 5
    min_samples: 3
    cluster_selection_epsilon: 0.1
  hyperparameter_tuning:
    enabled: true
    n_trials: 100
    study_name: "clustering_optimization"
    save_optimization_results: true
    optimization_results_path: "models/optimization_results.joblib"
  model_persistence:
    enabled: true
    model_dir: "models/clustering"
    retrain_threshold: 0.1
    drift_detection: true

vector_store:
  type: "faiss"  # or "chroma"
  index_path: "data/vector_store"
  similarity_metric: "cosine"

theme_analysis:
  max_samples_per_cluster: 10
  classification_threshold: 0.7 